"""Create a new simulation directory with all necessary files."""
from __future__ import annotations
import shutil
from pathlib import Path

from .config import SimConfig, UserConfig
from .sequence import generate_dna_sequence_txt
from .acetylate import acetylate_file

_DATA_DIR = Path(__file__).parent / "data"

# Filename of the coordinate data file inside setup_stage/ for each histone.
# window_setup_no_LH.py always looks for nucl_no_LH.txt, so we also write that
# name regardless; but for histones that use nucl.txt in in.nucl we copy both.
_DATA_FILENAME: dict[str, str] = {
    "1KX5": "nucl_no_LH.txt",
    "H3K56ac": "nucl_no_LH.txt",
    "H3K56acH4K77acH4K79ac": "nucl_no_LH.txt",
    "CENPA": "nucl.txt",
    "H2AZ": "nucl.txt",
    "macroH2A": "nucl.txt",
}

# First and last DNA atom IDs used by setup60colvars.py (from number.txt per histone).
_COLVARS_ATOMS: dict[str, tuple[int, int]] = {
    "1KX5": (1169, 1799),
    "H3K56ac": (1169, 1799),
    "H3K56acH4K77acH4K79ac": (1169, 1799),
    "CENPA": (994, 1624),
    "H2AZ": (987, 1617),
    "macroH2A": (1453, 2083),
}


def _data(histone: str, filename: str) -> Path:
    """Return path to a bundled data file, with a clear error if missing."""
    path = _DATA_DIR / histone / filename
    if not path.exists():
        raise FileNotFoundError(
            f"Bundled file '{filename}' not found for histone '{histone}'.\n"
            f"Expected: {path}\n"
            f"Add the file to pulling_sim/data/{histone}/ and reinstall."
        )
    return path


def _template_histone(sim_cfg: SimConfig) -> str:
    """
    Return the histone directory whose in.nucl / in.nucl_umbrella templates to use.
    When acetylation is requested on a base-1KX5 system we use the H3K56ac templates
    (which already contain `set type 43 mass ...`).
    """
    if sim_cfg.acetylation.enabled:
        return "H3K56ac"
    return sim_cfg.histone


def _generate_umbrella_inputs_script(sim_dir: Path, log_filename: str) -> None:
    """
    Write a self-contained generate_umbrella_inputs.py into sim_dir.
    The slurm job calls this script directly — no package import needed on the node.
    The script reads its own bundled in.nucl_umbrella template (copied next to it)
    and bond_coeff lines from setup_stage/{log_filename}.
    """
    content = f"""\
#!/usr/bin/env python3
\"\"\"
Auto-generated by pulling-sim setup.
Run from sim_dir to produce in.nucl_1..5 for umbrella sampling.
\"\"\"
from pathlib import Path
import sys

sim_dir = Path(__file__).parent
template_path = sim_dir / "in.nucl_umbrella.template"
log_path = sim_dir / "setup_stage" / "{log_filename}"

if not template_path.exists():
    sys.exit(f"Template not found: {{template_path}}")
if not log_path.exists():
    sys.exit(f"Setup log not found: {{log_path}}\\nRun the setup SLURM job first.")

template = template_path.read_text()

coeffs = []
for line in log_path.read_text().splitlines():
    stripped = line.strip()
    if stripped.startswith("bond_coeff"):
        parts = stripped.split()
        if int(parts[1]) >= 4:
            coeffs.append(stripped)

if not coeffs:
    sys.exit(f"No sequence-specific bond_coeff lines found in {{log_path}}.")

bond_block = "\\n".join(coeffs)

for replica in range(1, 6):
    content = template.replace("###BOND_COEFFICIENTS###", bond_block)
    content = content.replace("###R###", str(replica))
    (sim_dir / f"in.nucl_{{replica}}").write_text(content)

print(f"Generated in.nucl_1..5 in {{sim_dir}} ({{len(coeffs)}} bond coefficients).")
"""
    (sim_dir / "generate_umbrella_inputs.py").write_text(content)


def _generate_slurm(sim_dir: Path, cfg: SimConfig, ucfg: UserConfig) -> None:
    """
    The setup job is submitted from setup_stage/ (so SLURM_SUBMIT_DIR = setup_stage/).
    After the 5 pulling simulations finish it runs the post-pull steps and submits slurm-umbrella.
    """
    job = cfg.job_setup
    a = ucfg.archer2
    content = f"""\
#!/bin/bash
#SBATCH -J pulling
#SBATCH --nodes={job.nodes}
#SBATCH --ntasks={job.ntasks}
#SBATCH --time={job.time}
#SBATCH --account={a.account}
#SBATCH --partition={a.partition}
#SBATCH --qos={a.qos}

cd "$SLURM_SUBMIT_DIR" || exit 1   # = setup_stage/

export OMP_NUM_THREADS=1
export LD_LIBRARY_PATH={a.ld_library_path}

echo -e "JobID: $SLURM_JOB_ID\\nTime: $(date)\\nHostname: $(hostname)\\nCurrent Directory: $(pwd)\\n======"

TASKS_PER_SCRIPT=32

for i in $(seq 1 5); do
    srun --cpu-freq=2250000 --exclusive -N1 -n$TASKS_PER_SCRIPT {a.lmp} -in in.nucl_${{i}} > out_${{i}}.txt 2>&1 &
done
wait

echo "====== Pulling done. Running post-pull setup... ======"

module load cray-python

mkdir -p data_start_files_no_LH
python window_setup_no_LH.py
mv data_start_files_no_LH ../

cd ..   # now in sim_dir

# Generate umbrella in.nucl_1..5 from bond coefficients in the setup log
python generate_umbrella_inputs.py

bash paste2.sh
python setup60colvars.py

echo "====== Submitting umbrella job ======"
sbatch slurm-umbrella
"""
    (sim_dir / "slurm").write_text(content)


def _generate_slurm_umbrella(sim_dir: Path, cfg: SimConfig, ucfg: UserConfig) -> None:
    job = cfg.job_umbrella
    a = ucfg.archer2
    n_windows = 60
    content = f"""\
#!/bin/bash
#SBATCH -J umbrella_{cfg.histone}_{cfg.sequence.name}
#SBATCH --nodes={job.nodes}
#SBATCH --ntasks={job.ntasks}
#SBATCH --time={job.time}
#SBATCH --account={a.account}
#SBATCH --partition={a.partition}
#SBATCH --qos={a.qos}

cd "$SLURM_SUBMIT_DIR" || exit 1

export OMP_NUM_THREADS=1
export LD_LIBRARY_PATH={a.ld_library_path}
export SLURM_CPU_FREQ_REQ=2250000

echo -e "JobID: $SLURM_JOB_ID\\nTime: $(date)\\nHostname: $(hostname)\\nCurrent Directory: $(pwd)\\n======"

TASKS_PER_SIM=32

for i in $(seq 1 {n_windows}); do
    for j in $(seq 1 5); do
        (
            cd "${{i}}" || exit
            srun --exclusive -N1 -n$TASKS_PER_SIM {a.lmp} -in in.nucl_${{j}} > out_${{j}}.txt 2>&1
        ) &
    done
done

wait
"""
    (sim_dir / "slurm-umbrella").write_text(content)


def _generate_paste2(sim_dir: Path, ucfg: UserConfig, n_windows: int = 60) -> None:
    """Run from sim_dir. Sources in.nucl_* and DNA files from setup_stage/."""
    a = ucfg.archer2
    lines = [
        "#!/bin/bash",
        "# Run from sim_dir after data_start_files_no_LH has been moved here.",
        f"for i in $(seq 1 {n_windows}); do",
        '    mkdir -p "${i}"',
        f'    cp -v "{a.chromatin_so}" "${{i}}/chromatin.so"',
        f'    cp -v "{a.lmp}" "${{i}}/lmp_archer2"',
    ]
    for fname in ["DNA_sequence.txt", "NAFlex_params.txt"]:
        lines.append(f'    cp -v "setup_stage/{fname}" "${{i}}/"')
    for j in range(1, 6):
        # in.nucl_1..5 at sim_dir root are the UMBRELLA inputs (generated post-setup)
        lines.append(f'    cp -v "in.nucl_{j}" "${{i}}/"')
    for j in range(1, 6):
        lines.append(
            f'    cp -v "data_start_files_no_LH/data_file_{j}_${{i}}.txt" "${{i}}/nucl_{j}.txt"'
        )
    lines.append("done")
    (sim_dir / "paste2.sh").write_text("\n".join(lines) + "\n")


def _generate_setup60colvars(sim_dir: Path, atom1: int, atom2: int, n_windows: int = 60) -> None:
    content = f"""\
import numpy as np
import os

hi = 725
lo = 25
Nwindows = {n_windows}
v0s = np.linspace(lo, hi, Nwindows)

base_dir = os.path.dirname(os.path.abspath(__file__))

for w, v0 in zip(range(1, Nwindows + 1), v0s):
    path = os.path.join(base_dir, str(w), "colvars_settings.txt")
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as fh:
        fh.write("colvar {{\\n")
        fh.write("\\tname dist\\n")
        fh.write("\\tdistance {{\\n")
        fh.write("\\t\\tgroup1 {{ atomNumbers {atom1} }}\\n")
        fh.write("\\t\\tgroup2 {{ atomNumbers {atom2} }}\\n")
        fh.write("\\t}}\\n")
        fh.write("}}\\n")
        fh.write("harmonic {{\\n")
        fh.write("\\tcolvars dist\\n")
        fh.write(f"\\tcenters {{v0}}\\n")
        fh.write("\\tforceConstant 0.025\\n")
        fh.write("}}\\n")
        fh.write(" ")
"""
    (sim_dir / "setup60colvars.py").write_text(content)


def _generate_run_all(sim_dir: Path) -> None:
    """Single script the user runs to kick off the entire workflow."""
    content = """\
#!/bin/bash
# Run this script once to launch the full nucleosome pulling + umbrella workflow.
# It generates LAMMPS input files, submits the setup job, and that job will
# automatically submit the umbrella job when it finishes.

set -e
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo "=== Generating LAMMPS input files (setup.sh) ==="
cd "$SCRIPT_DIR/setup_stage"
bash setup.sh

echo "=== Submitting setup pulling job ==="
# Submit from setup_stage so SLURM_SUBMIT_DIR points there
JOB_ID=$(sbatch --parsable "$SCRIPT_DIR/slurm")
echo "Setup job submitted: $JOB_ID"
echo "When it completes it will automatically submit the umbrella job."
"""
    run_all = sim_dir / "run_all.sh"
    run_all.write_text(content)
    run_all.chmod(0o755)


def build_simulation(sim_cfg: SimConfig, user_cfg: UserConfig, output_dir: Path, sim_yaml_src: Path | None = None) -> Path:
    """
    Create {output_dir}/{HISTONE}_{SEQ_NAME}/ with all files needed to run the workflow.
    Returns the created simulation directory path.
    """
    histone = sim_cfg.histone
    tmpl_histone = _template_histone(sim_cfg)  # H3K56ac when acetylation enabled
    sim_name = f"{histone}_{sim_cfg.sequence.name}"
    sim_dir = output_dir / sim_name

    if sim_dir.exists():
        raise FileExistsError(f"Simulation directory already exists: {sim_dir}")

    stage_dir = sim_dir / "setup_stage"
    stage_dir.mkdir(parents=True)

    # Copy bundled template files into setup_stage/
    # Use tmpl_histone for in.nucl (which may differ when acetylation uses H3K56ac templates)
    shutil.copy2(_data(tmpl_histone, "in.nucl"), stage_dir / "in.nucl")
    shutil.copy2(_data(histone, "NAFlex_params.txt"), stage_dir / "NAFlex_params.txt")

    # Copy coordinate data file.
    # window_setup_no_LH.py always expects nucl_no_LH.txt; in.nucl for CENPA/H2AZ/macroH2A
    # expects nucl.txt.  We write both names so both tools find what they need.
    data_fname = _DATA_FILENAME.get(histone, "nucl_no_LH.txt")
    src_data = _data(histone, data_fname)
    shutil.copy2(src_data, stage_dir / "nucl_no_LH.txt")
    if data_fname != "nucl_no_LH.txt":
        shutil.copy2(src_data, stage_dir / data_fname)

    shutil.copy2(_data(histone, "window_setup_no_LH.py"), stage_dir / "window_setup_no_LH.py")

    # Generate setup.sh
    setup_sh = (
        "for i in {1..5}\ndo\n"
        "\tsed \"s/XXX/${RANDOM}/g\" in.nucl > in.nucl_${i}\n"
        "\tsed -i \"s/YYY/${i}/g\" in.nucl_${i}\n"
        "done\n"
    )
    (stage_dir / "setup.sh").write_text(setup_sh)
    (stage_dir / "setup.sh").chmod(0o755)

    # Generate DNA_sequence.txt
    generate_dna_sequence_txt(
        dna=sim_cfg.sequence.dna,
        histone=histone,
        out_path=stage_dir / "DNA_sequence.txt",
    )

    # Apply acetylation if requested (overwrites nucl_no_LH.txt in place)
    if sim_cfg.acetylation.enabled:
        src = stage_dir / "nucl_no_LH.txt"
        tmp = stage_dir / "nucl_no_LH_orig.txt"
        src.rename(tmp)
        acetylate_file(
            input_path=tmp,
            output_path=src,
            acetyl_sites=sim_cfg.acetylation.sites,
        )
        tmp.unlink()
        # Keep nucl.txt in sync if it exists (CENPA/H2AZ/macroH2A case)
        if data_fname != "nucl_no_LH.txt":
            shutil.copy2(src, stage_dir / data_fname)

    # Symlink chromatin.so and lmp_archer2 into setup_stage/
    (stage_dir / "chromatin.so").symlink_to(Path(user_cfg.archer2.chromatin_so))
    (stage_dir / "lmp_archer2").symlink_to(Path(user_cfg.archer2.lmp))

    # Save a copy of the sim config so post-pull can read the histone type
    if sim_yaml_src is not None:
        shutil.copy2(sim_yaml_src, sim_dir / "sim.yaml")

    # Copy umbrella template to sim_dir so the standalone script can use it without
    # needing the package installed on compute nodes.
    shutil.copy2(_data(tmpl_histone, "in.nucl_umbrella"), sim_dir / "in.nucl_umbrella.template")

    # Determine colvars atom IDs for this histone
    atom1, atom2 = _COLVARS_ATOMS.get(histone, (1169, 1799))

    # Generate top-level scripts
    _generate_umbrella_inputs_script(sim_dir, "log.nucl_1.txt")
    _generate_slurm(sim_dir, sim_cfg, user_cfg)
    _generate_slurm_umbrella(sim_dir, sim_cfg, user_cfg)
    _generate_paste2(sim_dir, user_cfg)
    _generate_setup60colvars(sim_dir, atom1, atom2)
    _generate_run_all(sim_dir)

    return sim_dir
